[package]
name = "rust-atcoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# A問題
[[bin]]
name = "abc333"
path = "src/A/abc333.rs"

# B問題
[[bin]]
name = "trained"
path = "src/B/trained.rs"
